### ISSUE TITLE
How to create a my instance of chainbb 

### ISSUE THREAD

**Issue by hichemfetoui** [aaroncox/chainbb#38]
if it's allowed how can i run my own instance of chainbb

**Comment by aaroncox** [comment]
Currently there's no easy way to do it, it's not at the point where it's an install + host. There's also no documentation yet since it's still a relatively immature project. Hopefully all of this will come as it develops further and make this an easier question to answer!

In the mean time, if you're looking to use it, you're on your own.

**Comment by hichemfetoui** [comment]
thank you for your reply
